### ISSUE TITLE
Wrong configurator, out of order

### ISSUE THREAD

**Issue by phatboyg** [johncyril/MassTransit_RetryBugReproduction#1]
https://github.com/johncyril/MassTransit_RetryBugReproduction/blob/master/MassTransitTestFailureNotification/Infrastructure/BusFactory.cs#L62

The .UseMessageRetry() needs to be on the endpoint configurator (ec), not the bus configurator. 

It also needs to be above the consumer configuration line, or it won't take affect.

Also, this was absolutely the most complex example possible for a simple error case, sorry. Took me way too long to even get it to start, and still never got it right. A single program.cs would have been a lot easier to troubleshoot.

**Comment by johncyril** [comment]
Many thanks for looking at this.
Apologies for the complex nature of the example. I'd split stuff up in some haste, thinking it would make things easier.
The example is very close to how we're using MT and in addition to your pointers I found a bug in the registration of the consumer which is what was causing the ConsumeFault<T> message to be called multiple times in the first instance.

Registering the consumer with InstancePerLifetimeScope() resovled this and alleviated the need for us to even check if we are in a retry.
